from langchain_community.chat_message_histories import SQLChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_openai import ChatOpenAI
from fastapi import FastAPI 
from pydantic import BaseModel
from app.message_history_db.create_message_history_db import Conversations
from app.chains.contextualize_chain import contextualize_chain
from app.chains.rag_chain import qa_prompt, format_docs, _combine_documents
from app.retriever_chroma import build_retriever
from langchain.globals import set_verbose
from operator import itemgetter
import dotenv